name: Build and Deply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Build Image
              run: docker build -t ${{ vars.SERVICE_NAME }}:lastest .

            - name: Tag Image
              run: docker tag ${{ vars.SERVICE_NAME }}:lastest ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.SERVICE_NAME }}:lastest

            - name: Push Image
              run: docker push ${{ vars.SERVICE_NAME }}:lastest

    deploy:
        runs-on: ubuntu-lastest

        environment: production

        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Run an Oracle Cloud Infrastructure (OCI) CLI command
              uses: oracle-actions/run-oci-cli-command@v1.3.0

            - name: Teste OCI
              run: oci -v