name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.SERVICE_NAME }}:latest

    deploy:
        runs-on: ubuntu-lastest
        needs: 'build'
        environment: production

        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ vars.OCI_CLI_REGION }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run an Oracle Cloud Infrastructure (OCI) CLI 
              uses: oracle-actions/run-oci-cli-command@v1.3.0
              with:
                command: 'oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLI_CLUSTER }} --file $HOME/.kube/config --region us-chicago-1 --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT'
          
            - name: Export KUBECONFIG
              run: export KUBECONFIG=$HOME/.kube/config

            - name: Setup Kubectl
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: $HOME/.kube/config
              with:
                args: 'get pods'