name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    # build:
    #     runs-on: ubuntu-latest

    #     environment: production

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2

    #         - name: Login to Docker Hub
    #           uses: docker/login-action@v3
    #           with:
    #             username: ${{ vars.DOCKER_HUB_USERNAME }}
    #             password: ${{ secrets.DOCKER_HUB_TOKEN }}

    #         - name: Setup Docker
    #           uses: docker/setup-buildx-action@v3

    #         - name: Build and Push
    #           uses: docker/build-push-action@v6
    #           with:
    #             context: .
    #             file: ./Dockerfile
    #             push: true
    #             tags: ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.SERVICE_NAME }}:latest

    deploy:
        runs-on: ubuntu-latest
        # needs: 'build'
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download OCI CLI
              run: curl -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh

            - name: Install OCI CLI
              run: bash install.sh --accept-all-defaults --install-dir ~/lib/oracle-cli

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Generate Config OCI CLI
              run: node ./scripts/createOCIConfig.js ${{ secrets.OCI_FILE_ID_PRIVATE_KEY }} ${{ secrets.OCI_CLI_USER }} ${{ secrets.OCI_CLI_FINGERPRINT }} ${{ secrets.OCI_CLI_TENANCY }} ${{ vars.OCI_CLI_REGION}}

            - name: Download Kubectl
              run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

            - name: Install Kubectl
              run: sudo install -o root -g root -m 0755 kubectl /home/runner/bin/kubectl

            - name: Test Kubectl
              run: |
                kubectl version --client

            - name: Export Kubeconfig
              run: |
                mkdir -p /home/runner/.kube
                echo "${{ secrets.KUBE_CONFIG }}" > /home/runner/.kube/config
                export KUBECONFIG=/home/runner/.kube/config
                export PATH=/home/runner/lib/oracle-cli/bin:$PATH
                kubectl get pods

            - name: Clear Files Privates OCI CLI
              run: rm -rf /home/runner/.oci
            
            - name: Clear Files Temp
              run: rm -rf ./scripts/tmp