name: Build and Deply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              run: echo ${{ vars.DOCKER_HUB_TOKEN }} | docker login -u ${{ vars.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Build Image
              run: docker build -t ${{ vars.SERVICE_NAME }}:lastest .

            - name: Tag Image
              run: docker tag ${{ vars.SERVICE_NAME }}:lastest ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.SERVICE_NAME }}:lastest

            - name: Push Image
              run: docker push ${{ vars.SERVICE_NAME }}:lastest

    deploy:
        runs-on: ubuntu-lastest

        environment: production

        env:
          OCI_CLI_USER: ${{ vars.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ vars.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ vars.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ vars.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ vars.OCI_CLI_REGION }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              run: echo ${{ vars.DOCKER_HUB_TOKEN }} | docker login -u ${{ vars.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Run an Oracle Cloud Infrastructure (OCI) CLI 
              uses: oracle-actions/run-oci-cli-command@v1.3.0
              with:
                command: 'oci ce cluster create-kubeconfig --cluster-id ${{ vars.OCI_CLI_CLUSTER }} --file $HOME/.kube/config --region us-chicago-1 --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT'
          
            - name: Export KUBECONFIG
              run: export KUBECONFIG=$HOME/.kube/config

            - name: Setup Kubectl
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: $HOME/.kube/config
              with:
                args: 'get pods'